name: sensor_bluetooth_app
description: "Una aplicación para rastreo de envíos y monitoreo de sensores con Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.0.0
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^11.3.0
  
  # --- NUEVO PAQUETE ---
  # Necesario para programar notificaciones en la zona horaria correcta.
  timezone: ^0.9.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
